export let basic = {
  spacing: [
    '0',
    'px',
    '0.5',
    '1',
    '1.5',
    '2',
    '2.5',
    '3',
    '3.5',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '14',
    '16',
    '20',
    '24',
    '28',
    '32',
    '36',
    '40',
    '44',
    '48',
    '52',
    '56',
    '60',
    '64',
    '72',
    '80',
    '96',
  ],

  colors: [
    'slate',
    'gray',
    'zinc',
    'neutral',
    'stone',
    'red',
    'orange',
    'amber',
    'yellow',
    'lime',
    'green',
    'emerald',
    'teal',
    'cyan',
    'sky',
    'blue',
    'indigo',
    'violet',
    'purple',
    'fuchsia',
    'pink',
    'rose',
  ],
  pseudoClass: [
    'hover',
    'focus',
    'focus-within',
    'focus-visible',
    'active',
    'visited',
    'target',
    'first',
    'last',
    'only',
    'odd',
    'even',
    'first-of-type',
    'last-of-type',
    'only-of-type',
    'empty',
    'disabled',
    'enabled',
    'checked',
    'indeterminate',
    'default',
    'required',
    'valid',
    'invalid',
    'in-range',
    'out-of-range',
    'placeholder-shown',
    'autofill',
    'read-only',
    'before',
    'after',
    'first-letter',
    'first-line',
    'marker',
    'selection',
    'file',
    'backdrop',
    'placeholder',
    'supports-[…]',
    'data-[…]',
    'rtl',
    'ltr',
    'open',
  ],
  pseudoClassmedia: [
    'sm',
    'md',
    'lg',
    'xl',
    '2xl',
    'min-[…]',
    'max-sm',
    'max-md',
    'max-lg',
    'max-xl',
    'max-2xl',
    'max-[…]',
    'dark',
    'portrait',
    'landscape',
    'motion-safe',
    'motion-reduce',
    'contrast-more',
    'contrast-less',
    'print',
  ],
  pseudoClassAria: [
    'aria-checked',
    'aria-disabled',
    'aria-expanded',
    'aria-hidden',
    'aria-pressed',
    'aria-readonly',
    'aria-required',
    'aria-selected',
    'aria-[…]',
  ],
  functions: [
    '@tailwind',
    '@apply',
    '@layer',
    '@config',
    'theme()',
    'screen()',
  ],
  variants: {
    'all-utility': ['responsive'],
    'background-color': ['hover', 'focus'],
    'border-color': ['hover', 'focus'],
    'box-shadow': ['hover', 'focus'],
    'font-weight': ['hover', 'focus'],
    opacity: ['hover', 'focus'],
    outline: ['focus'],
    'text-color': ['hover', 'focus'],
    'text-decoration': ['hover', 'focus'],
  },
  opacity: [0, 5, 10, 20, 25, 30, 40, 50, 60, 70, 75, 80, 90, 95, 100],
  colorsNum: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900],
};
